### ISSUE TITLE
error[E0425]: cannot find function `wheel_ev` in this scope

### ISSUE THREAD

**Issue by hiteshjoshi** [seed-rs/seed#661]
Hi, new to rust.

I get this error on your example code "canvas"

error[E0425]: cannot find function `wheel_ev` in this scope

I saw the changelog it talks about details on `wheel_ev` but I cannot find it.

**Comment by flosse** [comment]
`wheel_ev` is only available on the current master branch, not in seed `v0.8.0` so you should add this to your `Cargo.toml`:

```toml
[patch.crates-io]
seed = { git = "https://github.com/seed-rs/seed", branch="master" }
```
